### ISSUE TITLE
node version not working

### ISSUE THREAD

**Issue by freeman-lab** [BertrandBev/nlopt-js#1]
Hi! Super exciting package here! It could be really enabling for some of our efforts to do scientific computing in the browser. I've installed the version on npm and I have it working in the browser, but I'm having trouble using the same distribution from npm in `node`.

when i run the following in `node v14.7.0`

```
const nlopt = require('nlopt-js')

(async () => {
  await nlopt.ready
  const opt = new nlopt.Optimize(nlopt.Algorithm.LD_SLSQP, 2);
  opt.setMinObjective((x, grad) => {
    if (grad) {
      grad[0] = 0;
      grad[1] = 0.5 / Math.sqrt(x[1]);
    }
    return Math.sqrt(x[1]);
  }, 1e-4);
  const res = opt.optimize([1, 6]);
  nlopt.GC.flush();
})()
```

I get the error 
```
TypeError: require(...) is not a function
```

The import itself works, i.e. if I just try to run 

```
const nlopt = require('nlopt-js')
console.log(nlopt)
```

I get

```
{
  GC: [class D] { objects: Set(0) {}, whitelist: A { _data: {}, size: 0 } },
  ready: Promise { <pending> }
}
``` 

So something is working! But if I run the actual example, I get the error above. 

Maybe something went wrong with the `dist` version published to npm? Again, it does work in the browser!

Thanks for any ideas or help. I might also try rebuilding myself.

**Comment by BertrandBev** [comment]
Hi, sorry for the late reply!

This issue seems related to incompatibilities with node's require. Node v12 supports ES6 imports by default, so a quick fix is to save your scripts with a `.mjs` extension, or add a `"type": "module"` flag in your `package.json`, and it should run smoothly. I added a minimal example in the `./example` subfolder

Cheers!
